import mongoose, { Document, Schema } from "mongoose";
import { INVOICE_STATUSES, InvoiceStatus } from "../types/finance.types";

export interface IInvoiceDeactivation {
  warnedAt?: Date | null;
  deactivatedAt?: Date | null;
  reactivatedAt?: Date | null;
  reason?: string;
}

/**
 * Acuerdo de pago: el cliente se compromete a pagar en otra fecha dentro del mismo
 * período. Mueve el vencimiento de ESTA factura únicamente — el día de cobro del
 * cliente no cambia, así que el mes siguiente vuelve a su fecha habitual.
 */
export interface IInvoiceDeferral {
  previousDueDate: Date;
  newDueDate: Date;
  reason?: string;
  notes?: string;
  agreedAt: Date;
  agreedBy?: mongoose.Types.ObjectId;
  agreedByName?: string;
}

export interface IInvoice extends Document {
  _id: mongoose.Types.ObjectId;
  clientId: mongoose.Types.ObjectId;
  clientName: string;

  /** Período de cobro "YYYY-MM". */
  period: string;
  /** Índice del split dentro del período (0 cuando es cobro único). */
  splitIndex: number;
  splitLabel?: string;

  amount: number;
  currency: string;
  paidAmount: number;

  issueDate?: Date | null;
  dueDate: Date;
  /** Vencimiento original antes de la primera prórroga. */
  originalDueDate?: Date | null;
  deferrals: IInvoiceDeferral[];
  paidAt?: Date | null;

  /** Cobro adelantado: se paga antes de que arranque el período que cubre. */
  isAdvance: boolean;

  /**
   * Dinero devuelto sobre este cobro. No se descuenta de `paidAmount`: el pago
   * existió y la caja de ese mes no se reescribe. El neto es `paidAmount - refundedAmount`.
   */
  refundedAmount: number;
  refundedAt?: Date | null;

  /** Mes cubierto por una garantía: se emite en `waived`, sin cobro. */
  isGuarantee: boolean;
  guaranteeId?: mongoose.Types.ObjectId | null;

  status: InvoiceStatus;
  notes?: string;
  autoGenerated: boolean;

  reminderSentAt?: Date | null;
  overdueNotifiedAt?: Date | null;
  deactivation: IInvoiceDeactivation;

  workspaceId?: string | null;
  createdBy?: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const deactivationSchema = new Schema<IInvoiceDeactivation>(
  {
    warnedAt: { type: Date, default: null },
    deactivatedAt: { type: Date, default: null },
    reactivatedAt: { type: Date, default: null },
    reason: { type: String },
  },
  { _id: false }
);

const deferralSchema = new Schema<IInvoiceDeferral>(
  {
    previousDueDate: { type: Date, required: true },
    newDueDate: { type: Date, required: true },
    reason: { type: String, trim: true },
    notes: { type: String, trim: true },
    agreedAt: { type: Date, default: () => new Date() },
    agreedBy: { type: Schema.Types.ObjectId, ref: "User" },
    agreedByName: { type: String },
  },
  { _id: false }
);

const invoiceSchema = new Schema<IInvoice>(
  {
    clientId: { type: Schema.Types.ObjectId, ref: "Client", required: true, index: true },
    clientName: { type: String, required: true },

    period: { type: String, required: true, index: true },
    splitIndex: { type: Number, default: 0 },
    splitLabel: { type: String },

    amount: { type: Number, required: true, min: 0 },
    currency: { type: String, default: "USD" },
    paidAmount: { type: Number, default: 0, min: 0 },

    issueDate: { type: Date, default: null },
    dueDate: { type: Date, required: true, index: true },
    originalDueDate: { type: Date, default: null },
    deferrals: { type: [deferralSchema], default: [] },
    paidAt: { type: Date, default: null },
    isAdvance: { type: Boolean, default: false },

    refundedAmount: { type: Number, default: 0, min: 0 },
    refundedAt: { type: Date, default: null },

    isGuarantee: { type: Boolean, default: false, index: true },
    guaranteeId: { type: Schema.Types.ObjectId, ref: "Guarantee", default: null },

    status: {
      type: String,
      enum: INVOICE_STATUSES,
      default: "pending",
      index: true,
    },
    notes: { type: String },
    autoGenerated: { type: Boolean, default: true },

    reminderSentAt: { type: Date, default: null },
    overdueNotifiedAt: { type: Date, default: null },
    deactivation: { type: deactivationSchema, default: () => ({}) },

    workspaceId: { type: String, default: null },
    createdBy: { type: Schema.Types.ObjectId, ref: "User" },
  },
  { timestamps: true, versionKey: false }
);

invoiceSchema.index({ clientId: 1, period: 1, splitIndex: 1 }, { unique: true });
invoiceSchema.index({ status: 1, dueDate: 1 });

export const Invoice = mongoose.model<IInvoice>("Invoice", invoiceSchema);
